// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hneywetfzjefegupflua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhuZXl3ZXRmemplZmVndXBmbHVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUxMDg1MTYsImV4cCI6MjA1MDY4NDUxNn0.z_TzGfi3agzu_jdHQOT_b_SpzrNrlE4WcEWMGcuzvdc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);